Repository typedb/typedb-console, pull requests merged in 2020-06, with the labels that each got.

#37 Update to 1.8 dependencies
  ConsoleSession.java
  dependencies/graknlabs/dependencies.bzl
  test/BUILD
  test/GraknConsoleIT.java
Labels: priority: blocker, type: refactor

#38 Remove extra logback inclusion
  BUILD
Labels: type: build, type: refactor

#39 Update various dependencies related to upgrading gRPC to 1.29.0
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: priority: blocker, type: build

#25 Fix excessive rebuilding
  .bazelrc
Labels: type: build

#43 Update CI image to Ubuntu 16 and bump build tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#45 Add console-deps deployment to repo as archive
  .circleci/config.yml
  .gitignore
  BUILD
  deployment.properties
Labels: priority: blocker

#47 Add deploy-console-distribution
  .circleci/config.yml
  BUILD
Labels: type: build
