Repository typedb/typedb-console, pull requests merged in 2020-04, with the labels that each got.

#26 Disable role Put behavior
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  printer/StringPrinter.java
  test/GraknConsoleIT.java
Labels: status: blocked, type: feature, type: refactor

#27 Remove flyingsilverfin deps
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#29 Upgrade to Bazel 3.0.0
  .bazelrc
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#30 Use new 1.7 client-java improvements
  BUILD
  ConsoleSession.java
  WORKSPACE
  config/logback/logback.xml
  dependencies/graknlabs/dependencies.bzl
  printer/Printer.java
  printer/StringPrinter.java
  test/GraknConsoleIT.java
Labels: priority: high, type: refactor

#32 Turn logging off again
  config/logback/logback.xml
Labels: priority: high, type: bug

#33 Migrate load relative path file in and bump deps
  dependencies/graknlabs/dependencies.bzl
  test/BUILD
  test/GraknConsoleIT.java
  test/invalid-data.gql
Labels: type: refactor
