Repository typedb/typedb-console, pull requests merged in 2021-04, with the labels that each got.

#144 Add 'database schema' to help command and README
  README.md
  command/ReplCommand.java
Labels: priority: medium, type: bug, type: documentation

#145 Update Client Java and Grakn Core artifact
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: build

#147 Fix printing colored test under Windows
  BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: bug

#150 Transaction REPL checks arguments
  GraknConsole.java
  command/TransactionReplCommand.java
  common/exception/ErrorMessage.java
Labels: priority: medium, type: feature
