Repository typedb/typedb-console, pull requests merged in 2021-01, with the labels that each got.

#89 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#90 Unify the code used for printing answer
  GraknConsole.java
Labels: type: refactor

#91 Update client java
  dependencies/graknlabs/repositories.bzl
Labels: type: bug

#92 Bump year in license headers to 2021
  .bazelrc
  .gitignore
  .grabl/automation.yml
  BUILD
  GraknConsole.java
  WORKSPACE
  command/ReplCommand.java
  command/TransactionReplCommand.java
  common/Printer.java
  common/Utils.java
  conf/logback/BUILD
  conf/logback/logback.xml
  conf/rpm/BUILD
  conf/rpm/grakn-console.spec
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/update.sh
  deployment.bzl
  templates/BUILD
  templates/Version.java
Labels: type: build

#101 Fix incorrect UI for roles and variables names
  BUILD
  common/Printer.java
Labels: priority: high, type: bug

#103 Update maven dependencies
  dependencies/maven/artifacts.snapshot
Labels: priority: medium, type: bug

#104 Fix console exitting when trying to open transaction to a database that doesn't exist
  dependencies/graknlabs/repositories.bzl
Labels: type: bug

#105 Allow pasting multiline input
  command/ReplCommand.java
  command/TransactionReplCommand.java
  common/Utils.java
Labels: type: bug

#111 Add Grakn Cluster support
  .grabl/automation.yml
  GraknConsole.java
  common/Printer.java
  conf/logback/logback.xml
  dependencies/graknlabs/repositories.bzl
Labels: type: feature

#114 Fix Grakn Console distribution for Windows
  BUILD
Labels: type: bug, type: build

#115 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build
