Repository typedb/typedb-console, pull requests merged in 2021-02, with the labels that each got.

#117 Terminate console in the middle of the current answer calculation
  GraknConsole.java
Labels: type: feature

#120 Fix console not able to shutdown on exit and not close errored transaction
  GraknConsole.java
Labels: type: bug

#123 Refactor code to work with latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#124 Make console scriptable
  GraknConsole.java
  README.md
  command/ReplCommand.java
  command/TransactionReplCommand.java
Labels: type: feature

#125 Always deploy artifacts bundled together with a shell startup script
  .grabl/automation.yml
  BUILD
Labels: type: build

#126 Add 'database replicas' command
  GraknConsole.java
  command/ReplCommand.java
  common/Printer.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: feature

#128 Add option to read from any replica in Cluster
  GraknConsole.java
  command/ReplCommand.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: feature

#129 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#130 Bump dependencies for alpha-7 release
  VERSION
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#131 Allow specifying commands from command line without using script
  GraknConsole.java
  README.md
Labels: type: feature
