Repository typedb/typedb-console, pull requests merged in 2021-03, with the labels that each got.

#122 Remove RPM targets
  .grabl/automation.yml
  BUILD
  conf/rpm/BUILD
  conf/rpm/grakn-console.spec
Labels: priority: high, type: build, type: refactor

#135 Introduce transaction options
  BUILD
  GraknConsole.java
  command/ReplCommand.java
  common/exception/GraknConsoleException.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: feature

#136 Update client-java
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#137 Actually save transaction option parameters to fields
  command/ReplCommand.java
Labels: priority: blocker, type: bug

#138 When closing a READ transaction, simply print "transaction closed"
  GraknConsole.java
Labels: priority: low, type: bug

#142 Tweak location of console libraries
  BUILD
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build, type: refactor

#143 Add ability to print database schema
  GraknConsole.java
  VERSION
  command/ReplCommand.java
  common/Printer.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: high
