Repository typedb/typedb-console, pull requests merged in 2023-04, with the labels that each got.

#201 Prompt a re-login when users change their own passwords
  TypeDBConsole.java
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high

#202 Change wording of password expiry warning
  TypeDBConsole.java
Labels: type: feature, priority: medium

#203 Update dependencies for 2.17.0 release
  BUILD
  TypeDBConsole.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, priority: high
