Repository typedb/typedb-console, pull requests merged in 2024-01, with the labels that each got.

#223 Implement error diagnostics
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  BUILD
  TypeDBConsole.java
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
Labels: priority: high

#224 Reconfigure CircleCI executors
  .bazelrc
  .circleci/config.yml
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
Labels: type: build, type: refactor, priority: high

#222 Bring in launch binary and console runner library from common
  .factory/automation.yml
  .gitattributes
  BUILD
  WORKSPACE
  binary/BUILD
  binary/typedb
  binary/typedb.bat
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/assembly/AssemblyTest.java
  test/assembly/BUILD
  tool/runner/BUILD
  tool/runner/TypeDBConsoleRunner.java
  tool/runner/Util.java
Labels: type: refactor, priority: medium

#226 Remove typedb-console-runner's dependency on typedb-common
  tool/runner/BUILD
  tool/runner/TypeDBConsoleRunner.java
Labels: priority: medium

#225 Migrate artifact hosting to cloudsmith
  .circleci/config.yml
  .circleci/windows/deploy_release.bat
  .circleci/windows/deploy_snapshot.bat
  .factory/automation.yml
  BUILD
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  tool/runner/BUILD
Labels: type: build

#227 Make console runner use the same java installation as the calling process
  tool/runner/TypeDBConsoleRunner.java
Labels: type: build

#228 Allow unicode TypeQL variables
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: type: feature, priority: medium

#229 Sync dependencies in CI
  .circleci/config.yml
  .factory/automation.yml
Labels: type: build, priority: high

#230 Explicitly install python tool dependencies
  BUILD
  WORKSPACE
Labels: type: build, priority: high

#231 Use typedb-common from typeql/common, only deploy to CloudSmith
  .circleci/config.yml
  .circleci/windows/deploy_release.bat
  .factory/automation.yml
  BUILD
  RELEASE_TEMPLATE.md
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, priority: blocker

#232 Update VERSION to 2.26.6-rc1 and create release notes
  RELEASE_NOTES_LATEST.md
  RELEASE_TEMPLATE.md
  VERSION
Labels: priority: high
