Repository typedb/typedb-console, pull requests merged in 2025-01, with the labels that each got.

#271 Fix printing of variables with empty values and rows with no columns
  TypeDBConsole.java
  common/Printer.java
Labels: type: bug, type: refactor

#272 Prepare release 3.0.4
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/typedb/repositories.bzl
Labels: type: build

#273 Update the Driver dependency to work with optional concepts from rows
  common/Printer.java
  dependencies/typedb/repositories.bzl
Labels: type: refactor
