Repository typedb/typedb-console, pull requests merged in 2025-04, with the labels that each got.

#280 Add `user list` command
  src/main.rs
  src/operations.rs
Labels: type: feature, priority: high

#283 Update typedb-driver dependency for token-based authentication and version to 3.2.0-rc0
  Cargo.toml
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/typedb/repositories.bzl
  tool/runner/Cargo.toml
Labels: priority: high

#284 Improve multiline query support
  BUILD
  Cargo.lock
  Cargo.toml
  README.md
  WORKSPACE
  dependencies/typedb/repositories.bzl
  src/main.rs
  src/operations.rs
  src/repl/command.rs
Labels: type: feature, priority: medium

#289 Increase transaction timeout
  src/constants.rs
  src/main.rs
  src/operations.rs
Labels: type: feature
